--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CzechPMDevs/SmallPlugins
branches:
- master
projects:
  ServerTransfer:
    path: ServerTransfer/
  WelcomeMessage:
    path: WelcomeMessage/
  UnlimitedSlots:
    path: UnlimitedSlots/
  BlockInfo:
    path: BlockInfo/
...
