name: ServerTransfer
api: [3.0.0, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
version: 1.0.0
author: GamakCZ
main: ServerTransfer\Main
description: Simple Transfer plugin

commands:
  transfer:
    description: Transfer player to another server
    aliases:
      - servertransfer

permissions:
  st.transfer:
    description: transfer to other servers
    default: op
  st.transfer.other: 
    description: transferother players to other servers
    default: op
