name: SimpleHome
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0]
version: 1.0.3
main: czechpmdevs\simplehome\SimpleHome
author: CzechPMDevs
authors: [VixikCZ]
description: Simple home plugin
website: https://github.com/CzechPMDevs/SmallPlugins/SimpleHome

permissions:
  sh.limit:
    default: op
    description: Allows have count of unlimited homes
  sh.cmd:
    default: true
    description: Permissions to all SimpleHome commands
    childern:
      sh.cmd.sethome:
        default: true
        description: Permission for /sethome <home>
      sh.cmd.home:
        default: true
        description: Permission for /home <home>
      sh.cmd.delhome:
        default: true
        description: Permission for /delhome <home>
